[2023-09-27T08:31:12.563+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-27T08:31:12.576+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-27T08:31:12.577+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-09-27T08:31:12.598+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ScraperImmoWeb> on 2023-09-27 00:00:00+00:00
[2023-09-27T08:31:12.608+0000] {standard_task_runner.py:57} INFO - Started process 605 to run task
[2023-09-27T08:31:12.614+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ImmoElizaPipeline', 'ScraperImmoWeb', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/immoEliza.py', '--cfg-path', '/tmp/tmpqrgiyddn']
[2023-09-27T08:31:12.618+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask ScraperImmoWeb
[2023-09-27T08:31:12.681+0000] {task_command.py:415} INFO - Running <TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [running]> on host 729374979be2
[2023-09-27T08:31:12.779+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ImmoElizaPipeline' AIRFLOW_CTX_TASK_ID='ScraperImmoWeb' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-09-27T08:31:58.868+0000] {logging_mixin.py:151} INFO - Number of ids: 19980
[2023-09-27T08:31:58.886+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/immoEliza.py", line 9, in mainScraperImmoWeb
    id_scraper(search_pages_num)
  File "/opt/airflow/dags/scraper/id_scraper.py", line 68, in id_scraper
    save_to_txt(ids)
  File "/opt/airflow/dags/scraper/id_scraper.py", line 55, in save_to_txt
    with open(file_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/properties_ids.txt'
[2023-09-27T08:31:58.913+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=ImmoElizaPipeline, task_id=ScraperImmoWeb, execution_date=20230927T000000, start_date=20230927T083112, end_date=20230927T083158
[2023-09-27T08:31:58.931+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task ScraperImmoWeb ([Errno 2] No such file or directory: '/opt/airflow/data/properties_ids.txt'; 605)
[2023-09-27T08:31:58.961+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-27T08:31:58.977+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
