[2023-09-27T08:29:14.926+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-27T08:29:14.944+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-27T08:29:14.945+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-27T08:29:14.967+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ScraperImmoWeb> on 2023-09-27 00:00:00+00:00
[2023-09-27T08:29:14.975+0000] {standard_task_runner.py:57} INFO - Started process 561 to run task
[2023-09-27T08:29:14.981+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ImmoElizaPipeline', 'ScraperImmoWeb', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/immoEliza.py', '--cfg-path', '/tmp/tmpq8mocfij']
[2023-09-27T08:29:14.986+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask ScraperImmoWeb
[2023-09-27T08:29:15.061+0000] {task_command.py:415} INFO - Running <TaskInstance: ImmoElizaPipeline.ScraperImmoWeb scheduled__2023-09-27T00:00:00+00:00 [running]> on host 729374979be2
[2023-09-27T08:29:15.230+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ImmoElizaPipeline' AIRFLOW_CTX_TASK_ID='ScraperImmoWeb' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-09-27T08:29:42.043+0000] {logging_mixin.py:151} INFO - Number of ids: 19980
[2023-09-27T08:29:42.066+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/immoEliza.py", line 9, in mainScraperImmoWeb
    id_scraper(search_pages_num)
  File "/opt/airflow/dags/scraper/id_scraper.py", line 68, in id_scraper
    save_to_txt(ids)
  File "/opt/airflow/dags/scraper/id_scraper.py", line 55, in save_to_txt
    with open(file_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/properties_ids.txt'
[2023-09-27T08:29:42.100+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=ImmoElizaPipeline, task_id=ScraperImmoWeb, execution_date=20230927T000000, start_date=20230927T082914, end_date=20230927T082942
[2023-09-27T08:29:42.118+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task ScraperImmoWeb ([Errno 2] No such file or directory: '/opt/airflow/data/properties_ids.txt'; 561)
[2023-09-27T08:29:42.178+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-27T08:29:42.197+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
